on:
  push: {}
  schedule:
    - cron: '0 7 * * *'  # Runs daily at 7:00 AM UTC (8:00 AM WAT)

jobs:
  katsu-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      - name: Run Katsu Wallet API tests
        run: |
          OUTPUT=$(postman collection run "46224899-5d486da3-711e-4a2c-af97-b3ecaa0b23b8" -e "34441668-61ac56f0-4118-4b84-9cf1-c99e6e61816f")
          echo "$OUTPUT"
          SUMMARY_URL=$(echo "$OUTPUT" | grep -o 'https://go.postman.co/workspace[^ ]*' | head -n 1)
          if [ -z "$SUMMARY_URL" ]; then
            SUMMARY_URL="(Summary URL not found)"
          fi
          echo "SUMMARY_URL=$SUMMARY_URL" >> $GITHUB_ENV
      - name: Send Slack Notification
        if: always()
        run: |
          if [ "${{ job.status }}" = "success" ]; then
            STATUS=":white_check_mark: Katsu Wallet API Tests Passed!"
          else
            STATUS=":x: Katsu Wallet API Tests Failed!"
          fi

          curl -X POST -H 'Content-type: application/json' \
            --data "{
              \"text\": \"${STATUS}\nView Test Summary on Postman: ${{ env.SUMMARY_URL }}\"\n<'"$SUMMARY_URL"'|View Test Summary on Postman>
            }" \
            ${{ secrets.SLACK_WEBHOOK_URL }}
